CREATE TABLE IF NOT EXISTS rag_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    source_uri VARCHAR(1024),
    external_ref VARCHAR(255),
    title VARCHAR(512),
    content CLOB NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    indexed_generation BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    chunk_count INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    metadata CLOB NOT NULL DEFAULT '{}',
    last_error CLOB,
    last_attempted_at TIMESTAMP,
    indexed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rag_documents_source_uri_source_type
    ON rag_documents(source_uri, source_type);

CREATE TABLE IF NOT EXISTS rag_index_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    stage VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    version BIGINT NOT NULL DEFAULT 0,
    last_event VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    target_generation BIGINT,
    message_id VARCHAR(128),
    last_error CLOB,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_index_jobs_document_sha UNIQUE (document_id, content_sha256)
);

CREATE TABLE IF NOT EXISTS rag_index_job_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    job_id BIGINT,
    outbox_id BIGINT,
    content_sha256 CHAR(64) NOT NULL,
    from_state VARCHAR(32),
    to_state VARCHAR(32) NOT NULL,
    event VARCHAR(64) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    triggered_by VARCHAR(255),
    success BOOLEAN NOT NULL DEFAULT TRUE,
    failure_reason VARCHAR(64),
    error_message CLOB,
    message_id VARCHAR(128),
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_index_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    message_id VARCHAR(128),
    last_error CLOB,
    next_attempt_at TIMESTAMP,
    dispatched_at TIMESTAMP,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_index_outbox_document_sha_event UNIQUE (document_id, content_sha256, event_type)
);

CREATE TABLE IF NOT EXISTS rag_index_message_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(128) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    delivery_attempt INTEGER NOT NULL,
    failure_type VARCHAR(32) NOT NULL,
    error_message CLOB,
    payload_base64 CLOB,
    payload_preview CLOB,
    properties_json CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rag_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    product_id BIGINT,
    source_type VARCHAR(64),
    index_generation BIGINT NOT NULL DEFAULT 1,
    chunk_index INTEGER NOT NULL,
    chunk_type VARCHAR(64),
    heading_path CLOB,
    chunk_text CLOB NOT NULL,
    chunk_hash CHAR(64) NOT NULL,
    char_count INTEGER NOT NULL DEFAULT 0,
    token_count INTEGER,
    vector_id VARCHAR(128) NOT NULL,
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rag_chunks_document_generation_chunk UNIQUE (document_id, index_generation, chunk_index),
    CONSTRAINT uq_rag_chunks_vector_id UNIQUE (vector_id)
);

CREATE TABLE IF NOT EXISTS agent_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id VARCHAR(64) NOT NULL UNIQUE,
    correlation_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    request_id VARCHAR(64),
    user_message_id VARCHAR(64),
    assistant_message_id VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'RUNNING',
    user_message CLOB NOT NULL,
    intent VARCHAR(32),
    intent_source VARCHAR(16),
    intent_confidence DECIMAL(4, 3),
    slots_json CLOB NOT NULL DEFAULT '{}',
    tools_called CLOB NOT NULL DEFAULT '[]',
    cards_emitted CLOB NOT NULL DEFAULT '[]',
    generated_by_model BOOLEAN,
    answer_text CLOB,
    memory_summary CLOB,
    memory_summary_message_count INTEGER,
    memory_summary_model VARCHAR(64),
    tokens_in INTEGER,
    tokens_out INTEGER,
    latency_ms INTEGER,
    error_code VARCHAR(64),
    error_message CLOB,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT agent_turn_intent_source_chk
        CHECK (intent_source IN ('rule_l1', 'rule_l2', 'llm', 'fallback', 'workflow'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_turn_idempotency
    ON agent_turn(user_id, conversation_id, request_id);

CREATE INDEX IF NOT EXISTS idx_agent_turn_conv_started
    ON agent_turn(conversation_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_turn_user_started
    ON agent_turn(user_id, started_at DESC);

-- catalog product (H2 fallback：用 CLOB 模拟 PG 的 jsonb)
CREATE TABLE IF NOT EXISTS catalog_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(512) NOT NULL,
    brand VARCHAR(255),
    category VARCHAR(128) NOT NULL,
    sub_category VARCHAR(128),
    base_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    price_min DECIMAL(12, 2),
    price_max DECIMAL(12, 2),
    total_stock INTEGER NOT NULL DEFAULT 0,
    image_path CLOB,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    attributes_json CLOB NOT NULL DEFAULT '{}',
    raw_json CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_catalog_product_category ON catalog_product(category);
CREATE INDEX IF NOT EXISTS idx_catalog_product_sub_category ON catalog_product(sub_category);
CREATE INDEX IF NOT EXISTS idx_catalog_product_brand ON catalog_product(brand);

CREATE TABLE IF NOT EXISTS catalog_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    sku_index INTEGER NOT NULL DEFAULT 0,
    properties_json CLOB NOT NULL DEFAULT '{}',
    price DECIMAL(12, 2) NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    raw_json CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalog_sku_product_index UNIQUE (product_id, sku_index)
);

CREATE INDEX IF NOT EXISTS idx_catalog_sku_product_id ON catalog_sku(product_id);

CREATE TABLE IF NOT EXISTS catalog_product_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    knowledge_type VARCHAR(64) NOT NULL,
    title VARCHAR(512),
    content CLOB NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalog_product_knowledge_type UNIQUE (product_id, knowledge_type)
);

CREATE TABLE IF NOT EXISTS catalog_product_faq (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    faq_index INTEGER NOT NULL DEFAULT 0,
    question CLOB NOT NULL,
    answer CLOB NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalog_product_faq_product_index UNIQUE (product_id, faq_index)
);

CREATE TABLE IF NOT EXISTS catalog_product_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    review_index INTEGER NOT NULL DEFAULT 0,
    nickname VARCHAR(128),
    rating INTEGER,
    content CLOB NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    sentiment VARCHAR(16),
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalog_product_review_product_index UNIQUE (product_id, review_index)
);

CREATE TABLE IF NOT EXISTS catalog_attribute_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL DEFAULT 'EXTRACT_ATTRIBUTES',
    status VARCHAR(16) NOT NULL DEFAULT 'NEW',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    message_id VARCHAR(128),
    last_error CLOB,
    next_attempt_at TIMESTAMP,
    dispatched_at TIMESTAMP,
    consumed_at TIMESTAMP,
    metadata CLOB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalog_attribute_outbox_product_event UNIQUE (product_id, event_type)
);

CREATE INDEX IF NOT EXISTS idx_catalog_attr_outbox_status_next
    ON catalog_attribute_outbox(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_catalog_attr_outbox_product_id
    ON catalog_attribute_outbox(product_id);
